function(calib_set_default_warnings target)
    if (MSVC)
        target_compile_options(${target} PRIVATE /W4 /permissive- /Zc:__cplusplus /bigobj)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        if (CALIB_ENABLE_WERROR)
            target_compile_options(${target} PRIVATE -Werror)
        endif()
    endif()
endfunction()
